
public enum Choice {
	Start,
	Detaillant,
	Caissier,
	Client,
	Fournisseur,
	MenuDetaillant,
	MenuCaissier,
	ListerLesElementsEnDessousDuSeuil,
	ListerTousLesArticles,
	ListerTousLesFournisseurs,
	ImprimerLaliste,
	ModifierLesInformationsConcernantLesArticles,
	ModifierLesInformationsConcernantLesFournisseurs,
	AjouterUnNouveauArticle,
	AjouterUnNouveauFournisseur,
	SupprimerUnArticle,
	SupprimerUnFournisseur,
	AnnulerLaCommande,
	PasserUneCommande,
	ChangerLeNomDuMagasin,
	ChangerMonNom,
	Quit
}
